<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from aip/xml/schema/CRM/Aip/Process.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ae7950196520c208d145cf0ca2d1776d)
 */
use CRM_Aip_ExtensionUtil as E;

/**
 * Database access object for the Process entity.
 */
class CRM_Aip_DAO_Process extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_aip_process';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Process ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Process Name
   *
   * @var string|null
   *   (SQL type: varchar(96))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Is this process enabled for scheduled runs?
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Date and time that sessions starts.
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $last_run;

  /**
   * Process Class Name
   *
   * @var string|null
   *   (SQL type: varchar(96))
   *   Note that values will be retrieved from the database as a string.
   */
  public $class;

  /**
   * JSON configuration for the process configuration
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $config;

  /**
   * JSON state of the process
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $state;

  /**
   * Human-readable documentation of what the process does.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $documentation;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_aip_process';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Processes') : E::ts('Process');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'aip_id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Process ID'),
          'required' => TRUE,
          'where' => 'civicrm_aip_process.id',
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'aip_name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Process Name'),
          'maxlength' => 96,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_aip_process.name',
          'export' => TRUE,
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'aip_is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active'),
          'description' => E::ts('Is this process enabled for scheduled runs?'),
          'where' => 'civicrm_aip_process.is_active',
          'default' => '0',
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'aip_last_run' => [
          'name' => 'last_run',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Last execution of this process'),
          'description' => E::ts('Date and time that sessions starts.'),
          'import' => TRUE,
          'where' => 'civicrm_aip_process.last_run',
          'export' => TRUE,
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'aip_class' => [
          'name' => 'class',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Implementation Class Name'),
          'description' => E::ts('Process Class Name'),
          'maxlength' => 96,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_aip_process.class',
          'export' => TRUE,
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'aip_config' => [
          'name' => 'config',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Process Configuration'),
          'description' => E::ts('JSON configuration for the process configuration'),
          'where' => 'civicrm_aip_process.config',
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 1,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
        'aip_state' => [
          'name' => 'state',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Process State'),
          'description' => E::ts('JSON state of the process'),
          'where' => 'civicrm_aip_process.state',
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 1,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
        'aip_documentation' => [
          'name' => 'documentation',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Process Documentation'),
          'description' => E::ts('Human-readable documentation of what the process does.'),
          'rows' => 8,
          'cols' => 60,
          'where' => 'civicrm_aip_process.documentation',
          'table_name' => 'civicrm_aip_process',
          'entity' => 'Process',
          'bao' => 'CRM_Aip_DAO_Process',
          'localizable' => 1,
          'html' => [
            'type' => 'RichTextEditor',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return CRM_Core_DAO::getLocaleTableName(self::$_tableName);
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'aip_process', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'aip_process', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
