-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_aip_process`;
DROP TABLE IF EXISTS `civicrm_aip_error_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_aip_error_log
-- *
-- * AIP Process
-- *
-- *******************************************************/
CREATE TABLE `civicrm_aip_error_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Process ID',
  `process_id` int unsigned COMMENT 'FK to AIP Process',
  `error_timestamp` datetime COMMENT 'Timestamp when the error was recorded',
  `error_message` text COMMENT 'The error message that was recorded with the processing failure',
  `data` text COMMENT 'Data set (record) to be processed',
  `is_resolved` tinyint DEFAULT 0 COMMENT 'Is this process enabled for scheduled runs?',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_aip_process
-- *
-- * AIP Process
-- *
-- *******************************************************/
CREATE TABLE `civicrm_aip_process` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Process ID',
  `name` varchar(96) COMMENT 'Process Name',
  `is_active` tinyint DEFAULT 0 COMMENT 'Is this process enabled for scheduled runs?',
  `last_run` datetime COMMENT 'Date and time that sessions starts.',
  `class` varchar(96) COMMENT 'Process Class Name',
  `config` text COMMENT 'JSON configuration for the process configuration',
  `state` text COMMENT 'JSON state of the process',
  `documentation` text COMMENT 'Human-readable documentation of what the process does.',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
